---
output: 
  html_document:
    df_print: paged
    highlight: tango
    theme: paper
    fig_width: 9
    fig_height: 5
---

<center> <h1>beltOfTools</h1> </center>
<center> <h3>Vásquez Guerra Carlos Fernando</h3> </center>
<center> <h4>5/28/2020</h4> </center>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Para trabajar con R, solo necesitamos instalar el lenguaje de programación directamente desde el [CRAN](https://www.r-project.org), después veremos que es esto. Aún así, para tener una mejor experiencia de este, les recomiendo descargar e instalar ciertas herramientas.

### RStudio

Con RStudio, lograremos hacer scripts y muchas más cosas relacionadas con R y otros lenguajes de programación. Al instalar este programa, no es necesario instalar de manera independiente el lenguaje de programación, con la propia instalación de esta IDE es más que suficiente.

De acuero al sistema operativo que tengan, pueden descarga de la página oficial de [RStudio](https://rstudio.com/products/rstudio/download/) este software (Con la versión gratuita es más que suficiente).

### LaTex

Además de archivos `.r`que haremos en RStudio, se pueden crear archivos PDF, HTML y hasta Word con la integración del sistema Markdown. Para los archivos HTML, como este donde estan leyendo, no existe gran problema en cuanto a los requerimientos; pero al hacer archivos PDF se requiere que tengan instalado alguna versión de LaTex.

Les recomiendo instalar el programa [TeXMaker](https://www.xm1math.net/texmaker/download.html) que les puede ser de utilidad en sesiones futuras para crear archivos directamente en el lenguaje LaTex. El tipo de instalación dependerá de su SO.

No se preocupen de no tener conocimiento de LaTex, poco a poco veremos algunas características relevantes.

### Comentarios

Por el momento, es suficiente con estas herramientas, si tienen algún problema no duden en consultarme, ya sea mediante contacto personal o el correo electrónico que se deja al final de este documento.

Les recomiendo visitar la página de [Rpubs](https://rpubs.com) para ver algunos trabajos que realiza la enorme comunidad de R día a día. También les dejo aquí la [Galería de RMarkdown](https://rmarkdown.rstudio.com/gallery.html) para que visualizen todas las cosas que se pueden lograr con RStudio. 

Finalmente, el contenido de este proyecto estará contenido en un repositorio público de [GitHub](https://github.com/CarlosFernandoVG/RFCMAY2020) donde pueden descargar todo el material. Bien pueden investigar sobre esta herramienta de gestionamiento de proyectos para que la integración entre ese repositorio y su computadora.

Sugerencias y comentarios al correo cvasquezfguerra@gmail.com
